stock:
  inner:
    - sh000001
    - sz399001
  outer:
    - int_dji
    - int_nasdaq
    - int_hangseng
    - int-nikkei
    - b_FSSTI
  upDownRange:
    - "<-7%"
    - "-7~-5%"
    - "-5~-3%"
    - "-3~0%"
    - "0~3%"
    - "3~5%"
    - "5~7%"
    - ">7%"
