stock:
  inner:
    - sh000001
    - sz399001
  outer:
    - int_dji
    - int_nasdaq
    - int_hangseng
    - int-nikkei
    - b_FSSTI
  marketUrl: http://hq.sinajs.cn/list=
  blockUrl: http://vip.stock.finance.sina.com.cn/q/view/newSinaHy.php

task:
  pool:
    corePoolSize: 5 # 核心线程数
    maxPoolSize: 20 # 设置最大线程数
    keepAliveSeconds: 300 # 设置线程活跃时间，单位秒
    queueCapacity: 100 # 设置队列容量