#数据库配置
spring:
  redis:
    host: 127.0.0.1     # Redis服务器地址
    database: 0         # Redis数据库索引（默认为0）
    port: 6379          # Redis服务器连接端口
#    password: ld123456  # Redis服务器连接密码（默认为空)
    lettuce:
      pool:
        max-wait: -1ms
        max-active: 8
        max-idle: 8
        min-idle: 1
    timeout: PT10S



